api/src/controllers/platform/update.ts, ops/install.sh
=> server: fix install wizard completion when telemetry is disabled

.github/workflows/build.yml, sdk/cpp/build.sh
=> build: ci for building server should auth to aws

app/package.json, app/src/app/core/services/auth.service.ts, app/src/app/home/pages/batch/page.component.ts, app/src/app/home/pages/suite/settings.component.html, app/src/app/home/pages/suite/settings.component.ts, app/yarn.lock
=> server: make retention field values more intuitive

api/src/utils/config.ts, web/pages/pricing.tsx
Related to #93 but does not fix it.
=> web: update pricing plans

api/src/controllers/suite/create.ts, api/src/routes/suite.ts
=> server: attemp to fix misleading suite creation error

README.md, sdk/python/touca/_runner.py, sdk/python/touca/cli/_post.py
=> sdk-python: CLI post sub-command should not expect merged files

.gitignore, sdk/python/touca/_options.py, sdk/python/touca/cli/_post.py
=> Python CLI post sub-command should respect config profile

.github/workflows/build.yml, cmp/build.sh
=> build: unpin gcovr package to use latest version

api/src/controllers/platform/config.ts, app/.prettierrc.js, app/.prettierrc.json, app/src/app/account/install.component.html, app/src/app/account/install/telemetry.component.html, app/src/app/account/install/telemetry.component.ts, app/src/app/account/install/thanks.component.html, app/src/app/account/settings/telemetry.component.html, app/src/app/account/settings/telemetry.component.ts, app/src/app/shared/components/checkbox.component.html, packages/api-schema/src/schema.yaml, web/.prettierrc.js, web/.prettierrc.json, web/components/atf.tsx, web/components/footer.tsx
=> server: rewrite telemetry tab of install workflow

app/src/app/home/pages/batch/page.component.html, app/src/app/home/pages/element/page.component.html, app/src/app/home/pages/suite/page.component.html, app/src/app/home/pages/team/page.component.html, app/src/styles.scss
=> server: make teams page width consistent with other pages

docs/docusaurus.config.js
=> docs: enable search using algolia

.gitignore, api/src/controllers/platform/config.ts, api/src/controllers/platform/health.ts, api/src/controllers/platform/install.ts, api/src/controllers/platform/stats.ts, api/src/controllers/platform/update.ts, api/src/server.ts, api/src/startup/index.ts, api/src/utils/config.ts, api/src/utils/mailer.ts, api/test/utils/config.test.ts, app/.prettierrc.js, app/src/app/account/account.module.ts, app/src/app/account/profile.component.html, app/src/app/account/profile.component.ts, app/src/app/account/settings/mail.component.html, app/src/app/account/settings/mail.component.ts, app/src/app/account/settings/telemetry.component.html, app/src/styles.scss, packages/api-schema/src/schema.yaml
=> server: add settings tab for configuring mail transport

docs/docs/cli/Readme.md, sdk/python/touca/cli/_plugin.py
=> docs: update cli commands

sdk/js/CHANGELOG.md, sdk/js/packages/node/src/client.ts, sdk/js/packages/node/src/runner.ts, sdk/js/packages/node/test/runner.test.ts
=> sdk-js: enable running multiple workflows

sdk/js/packages/node/src/runner.ts
=> sdk-js: change default output directory

sdk/js/CHANGELOG.md, sdk/js/packages/node/src/client.ts, sdk/js/packages/node/src/options.ts, sdk/js/packages/node/src/runner.ts, sdk/js/packages/node/src/transport.ts, sdk/js/packages/node/test/client.test.ts, sdk/js/packages/node/test/options.test.ts, sdk/js/packages/node/test/runner.test.ts, sdk/python/touca/_client.py
=> sdk-js: add support for automatic version increments

README.md, api/src/controllers/client/batchNext.ts, api/src/routes/client.ts, docs/docs/basics/Readme.mdx, docs/docs/basics/interpret.mdx, docs/docs/basics/submit.mdx, docs/docs/contributing/good-first-issues.mdx, packages/api-schema/src/schema.yaml, sdk/js/CHANGELOG.md, sdk/js/README.md, sdk/js/examples/01_node_minimal/README.md, sdk/js/package-lock.json, sdk/js/packages/node/package.json, sdk/js/packages/node/src/options.ts, sdk/js/packages/node/src/runner.ts, sdk/js/packages/node/src/transport.ts, sdk/js/packages/node/test/options.test.ts, sdk/js/packages/node/test/transport.test.ts, sdk/python/README.md, sdk/python/examples/01_python_minimal/README.md, sdk/python/touca/_printer.py
=> sdk-js: support configuration profiles

README.md, ops/install.sh, sdk/python/Changelog.md, sdk/python/touca/_transport.py, sdk/python/touca/cli/server.py
=> sdk-python: server install should default to using docker compose plugin

app/src/app/home/models/metric.model.ts, app/src/app/home/pages/batch/item.component.ts, app/src/app/home/pages/suite/item.component.ts, app/src/app/home/pages/team/item.component.ts, app/src/app/shared/pipes/datetime.pipe.ts
How performance changes are reported after this change:
=> server: improve how performance changes are described

sdk/python/touca/cli/check.py
https://user-images.githubusercontent.com/11810467/214380397-0753e7b8-a7ef-4550-b5ae-3b064afa5731.mp4
=> sdk-python: improve cli check command
